### ISSUE TITLE
Problem with module 'kornia'

### ISSUE THREAD

**Issue by jonghyun0921** [vcg-uvic/sportsfield_release#4]
Hi, I've just tried to follow your code.

While I was running the ipynb file you uploaded after setting the environment by environment.yml, I faced the problem below, although I did the previous settings without any failures;

![image](https://user-images.githubusercontent.com/66205529/87974841-a2832480-cb05-11ea-941d-4a0af2ff2790.png)

The code ran in colab instead of Jupyter Notebook.

**Comment by jiangwei221** [comment]
Have you tried to install kornia?
In the .yml file the is "kornia==0.1.3.post2" installed using pip.

One way to avoid installing kornia is:
replacing the following lines: https://github.com/vcg-uvic/sportsfield_release/blob/89c14b2e17f9b7d736ac5cdd4f0348bbfe2ddaee/utils/utils.py#L127-L132
with:
https://github.com/kornia/kornia/blob/0af8eb6aa9c1b40e6805fd3dd84b65d101cb55f8/kornia/geometry/transform/imgwarp.py#L161-L263

I only used get_perspective_transform from kornia package.

**Comment by jiangwei221** [comment]
added a new commit to solve it(if kornia is not found):
https://github.com/vcg-uvic/sportsfield_release/commit/106cb994029b25f266ed77b3f9cc7ae97dcd38d9
