### ISSUE TITLE
How to get the top-down-view image?

### ISSUE THREAD

**Issue by ngthanhtin** [vcg-uvic/sportsfield_release#5]
Hi, this repo is interesting, but I wonder how to get the top-down-view image like this:
[](url)
![tested_img](https://user-images.githubusercontent.com/17596799/101984794-0f6ea500-3cc7-11eb-8a38-bc16fa77d75f.png)

**Comment by jiangwei221** [comment]
Hi, once you obtained the homography `H` that warps the template to the video frame, you can take a inverse of `H`, and the `H_inv` should bring the video frame to the tamplate.

**Comment by jiangwei221** [comment]
Update: Added top-down view to the ipython notebook
